"""
visualize_circuits.py
=====================
Visualize 5 MPS training states as Qiskit quantum circuits.
Unitaries are sampled DIRECTLY from the pool generated by build_pool.py.

Workflow:
  1. Load pool from output/pool_D2.npz  (run build_pool.py first)
  2. Call sample_from_pool() → get indices k[j,q] and local_unitaries[j,q]
  3. For each sample j, build a Qiskit circuit where:
       bond (q, q+1) gets UnitaryGate( local_unitaries[j,q] )
       — the EXACT 4×4 matrix from pool[k[j,q]]
  4. Render and composite into a single figure

Run:
  python build_pool.py          # generate pool first
  python visualize_circuits.py  # then visualize

Requires: qiskit, matplotlib, pillow, pylatexenc
"""

import numpy as np
import sys, os, io
sys.path.insert(0, os.path.dirname(__file__))

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from PIL import Image
from qiskit import QuantumCircuit
from qiskit.circuit.library import UnitaryGate
from build_pool import load_pool, sample_from_pool

os.makedirs("output", exist_ok=True)

# ══════════════════════════════════════════════════════════════════
#  USER PARAMETERS  — adjust freely
# ══════════════════════════════════════════════════════════════════
POOL_PATH  = "output/pool_D2.npz"  # pool file from build_pool.py
N_QUBITS   = 4                      # number of qubits
N_SAMPLES  = 5                      # how many training states to visualize
SAMPLE_SEED = 7                     # RNG seed for sampling from pool
OUT_PATH    = "output/mps_circuits_5samples.png"
# ══════════════════════════════════════════════════════════════════

STYLE = {
    "backgroundcolor": "#ffffff",
    "linecolor":       "#1a1a2e",
    "textcolor":       "#1a1a2e",
    "gatefacecolor":   "#2a9d8f",
    "gatetextcolor":   "#ffffff",
    "margin":          [0.8, 0.4, 0.4, 0.4],
    "fontsize":        13,
    "subfontsize":     10,
}
BG     = "#f7f6f2"
TEAL   = "#2a9d8f"
DARK   = "#264653"
MUTED  = "#6c757d"
ORANGE = "#e76f51"


def build_mps_circuit(j, indices, local_unitaries, n_qubits):
    """
    Build Qiskit circuit for MPS training state |x_j>.

    Uses the EXACT sampled matrices from local_unitaries[j, q].
    Each bond (q, q+1) gets a 2-qubit UnitaryGate with label U[k]
    showing which pool entry k was drawn.

    For n=4 qubits: 3 gates on bonds (0,1), (1,2), (2,3).
    Barriers separate each bond gate for clarity.
    """
    qc = QuantumCircuit(n_qubits)
    for q in range(n_qubits - 1):
        k    = indices[j, q]
        U    = local_unitaries[j, q]        # (Dd, Dd) from pool[k]
        gate = UnitaryGate(U, label=f"U[{k}]")
        qc.append(gate, [q, q + 1])
        qc.barrier()
    return qc


def qc_to_image(qc):
    fig = qc.draw(output="mpl", style=STYLE, fold=-1,
                  plot_barriers=True, initial_state=True)
    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=160, bbox_inches="tight",
                facecolor="#ffffff", pad_inches=0.15)
    plt.close(fig)
    buf.seek(0)
    return Image.open(buf).convert("RGBA")


def build_composite(indices, local_unitaries, state_vectors,
                    circuit_imgs, n_samples):
    fig = plt.figure(figsize=(20, 28), facecolor=BG)

    fig.text(0.5, 0.985,
             "NFL Dataset 1 — MPS Circuit Visualization",
             ha="center", va="top", fontsize=18,
             fontweight="bold", color=DARK)
    fig.text(0.5, 0.974,
             "Pool: 100 Haar-random 4×4 local unitaries  (D=2, d=2, Dd=4)",
             ha="center", va="top", fontsize=12, color=MUTED)
    fig.text(0.5, 0.963,
             "5 training states |x_j⟩ sampled from pool  |  "
             "n=4 qubits  |  Each gate U[k] is the EXACT pool entry k",
             ha="center", va="top", fontsize=11, color=MUTED)
    fig.add_artist(plt.Line2D([0.03, 0.97], [0.955, 0.955],
                   color=DARK, lw=0.8, alpha=0.3,
                   transform=fig.transFigure))

    panel_h   = 0.155
    panel_gap = 0.018
    top_start = 0.945

    for j in range(n_samples):
        top    = top_start - j * (panel_h + panel_gap)
        bottom = top - panel_h
        k_used = indices[j, :3].tolist()

        fig.text(0.03, top - 0.004,
                 f"Sample  j = {j}      |x_{j}⟩",
                 fontsize=13, fontweight="bold", color=TEAL, va="top")
        fig.text(0.18, top - 0.004,
                 f"Pool indices used:  bond(0,1) → U[{k_used[0]}]   "
                 f"bond(1,2) → U[{k_used[1]}]   "
                 f"bond(2,3) → U[{k_used[2]}]",
                 fontsize=10.5, color=DARK, va="top")
        norm_val = float(np.linalg.norm(state_vectors[j]))
        fig.text(0.78, top - 0.004,
                 f"‖|x_{j}⟩‖ = {norm_val:.4f}",
                 fontsize=10.5, color=ORANGE, va="top")

        ax = fig.add_axes([0.05, bottom + 0.01, 0.92, panel_h - 0.025],
                          frameon=True)
        ax.set_xticks([]); ax.set_yticks([])
        for spine in ax.spines.values():
            spine.set_edgecolor("#dcd9d5"); spine.set_linewidth(0.8)
        ax.set_facecolor("#ffffff")
        ax.imshow(np.array(circuit_imgs[j]), aspect="auto")

        if j < n_samples - 1:
            fig.add_artist(plt.Line2D(
                [0.03, 0.97], [bottom + 0.005, bottom + 0.005],
                color=DARK, lw=0.5, alpha=0.2,
                transform=fig.transFigure))

    fig.text(0.5, 0.018,
             "■ Teal U[k] = Haar-random unitary, pool entry k  "
             "| Barriers separate sequential bond gates  "
             "| Gate on bond (q,q+1) is a 4×4 unitary from pool",
             ha="center", fontsize=9.5, color=MUTED)
    fig.text(0.5, 0.007,
             "|x_j⟩ = contract( U[k_0] ⊗ U[k_1] ⊗ U[k_2] ) |0000⟩   "
             "(D=2, d=2)",
             ha="center", fontsize=9.5, color=DARK, style="italic")
    return fig


if __name__ == "__main__":

    # ── Step 1: Load pool from build_pool.py output ───────────────
    pool_data = load_pool(POOL_PATH)
    pool      = pool_data["pool"]
    meta      = pool_data["metadata"]
    print(f"Loaded pool: {pool.shape}  N={meta['N']}  D={meta['D']}  Dd={meta['Dd']}")

    # ── Step 2: Sample from pool ──────────────────────────────────
    samples = sample_from_pool(
        pool      = pool,
        n_qubits  = N_QUBITS,
        t_states  = N_SAMPLES,
        D         = meta["D"],
        d         = meta["d"],
        seed      = SAMPLE_SEED,
        verbose   = True,
    )
    indices         = samples["indices"]           # (N_SAMPLES, N_QUBITS)
    local_unitaries = samples["local_unitaries"]   # (N_SAMPLES, N_QUBITS, Dd, Dd)
    state_vectors   = samples["state_vectors"]     # (N_SAMPLES, 2^n)

    # ── Step 3: Build and render Qiskit circuits ──────────────────
    circuit_imgs = []
    for j in range(N_SAMPLES):
        qc  = build_mps_circuit(j, indices, local_unitaries, N_QUBITS)
        img = qc_to_image(qc)
        circuit_imgs.append(img)
        print(f"  Rendered |x_{j}>   k = {indices[j].tolist()}")

    # ── Step 4: Composite figure ──────────────────────────────────
    fig = build_composite(indices, local_unitaries, state_vectors,
                          circuit_imgs, N_SAMPLES)
    fig.savefig(OUT_PATH, dpi=150, bbox_inches="tight", facecolor=BG)
    plt.close(fig)
    print(f"\nSaved: {OUT_PATH}")
